const orderTypes = {
    ADD_TO_ORDER: 'ADD_TO_ORDER',


    GET_USER_ORDER_HISTORY: 'GET_USER_ORDER_HISTORY',
    SET_USER_ORDER_HISTORY: 'SET_USER_ORDER_HISTORY',

    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
    SET_ORDER_DETAIL: 'SET_ORDER_DETAIL'

    
}

export default orderTypes;