

const productsTypes = {
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCT_ID: 'FETCH_PRODUCT_ID',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCT: 'SET_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',


    UPDATE_NUMBER: 'UPDATE_NUMBER'
}

export default productsTypes;