

const productsTypes = {
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_HOME: 'FETCH_PRODUCTS_HOME',
    FETCH_PRODUCTS_FEATURE: 'FETCH_PRODUCTS_FEATURE',
    FETCH_PRODUCT_ID: 'FETCH_PRODUCT_ID',
    FETCH_PRODUCT_SELLER: 'FETCH_PRODUCT_SELLER',
    FETCH_PRODUCTS_RELATIVE: 'FETCH_PRODUCTS_RELATIVE',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_PRODUCTS_HOME: 'SET_PRODUCTS_HOME',
    SET_PRODUCTS_FEATURE: 'SET_PRODUCTS_FEATURE',
    SET_PRODUCTS_RELATIVE: 'SET_PRODUCTS_RELATIVE',
    SET_PRODUCT: 'SET_PRODUCT',
    SET_PRODUCT_SELLER: 'SET_PRODUCT_SELLER',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT',


    UPDATE_NUMBER: 'UPDATE_NUMBER',
    REDUCER_NUMBER: 'REDUCER_NUMBER',
    RESTORE_NUMBER: 'RESTORE_NUMBER',



    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',


    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',





    GET_PRODUCT_ID: 'GET_PRODUCT_ID',
    
}

export default productsTypes;