

const productsTypes = {
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_ID: 'FETCH_PRODUCTS_ID',
    SET_PRODUCT: 'SET_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    EDIT_PRODUCT: 'EDIT_PRODUCT'
}

export default productsTypes;